[package]
name = "morse"
version = "0.3.0"
authors = ["Pieter Vantorre <pietervantorre@gmail.com>", "Evan Pratten <ewpratten@gmail.com>", "Jorge Brunal Pérez <diniremix@gmail.com>"]
edition = "2021"

[dependencies]

[features]
norwegian = []
spanish = []
