[package]
name = "morse"
version = "0.2.0"
authors = ["Pieter Vantorre <pietervantorre@gmail.com>", "Evan Pratten <ewpratten@gmail.com>", "Torstein Nordgård-Hansen <torsteinnh@gmail.com>"]

[dependencies]

[features]
norwegian = []
